title: Tony Lai # your name (or website title) here
logo: "/images/photo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data professional with 2 years of experience in investment, E-commerce and sports analytics.
  <br><br>
  <a href="https://www.linkedin.com/in/tony-lai-mingwa//">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-B0RL5T8CLH # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
  
